fix: reduce use of `length/1` whenever not needed
Logflare/logflare pull request #1770
Opened 2023-10-23 09:53 UTC by hauleth

2023-10-23 18:19 UTC, Ziinc requested changes

2023-10-23 18:19 UTC, Ziinc commented on lib/logflare/logs/processor.ex
> +      :telemetry.span([:logflare, :logs, :processor, :ingest, :ingest], metadata, fn ->
```suggestion
      :telemetry.span([:logflare, :logs, :processor, :ingest, :store], metadata, fn ->
```

2023-10-23 18:19 UTC, Ziinc commented on lib/logflare/sources.ex
> +  def valid_source_token_param?(string) do
this uuid check should use this Ecto.UUID.dump instead, see here
https://github.com/Logflare/logflare/pull/1617

2023-10-23 18:19 UTC, Ziinc commented on lib/logflare/utils/list.ex
> +defmodule Logflare.Utils.List do
doctests missing

2023-10-26 13:40 UTC, Ziinc approved these changes

2023-10-26 13:41 UTC, Ziinc commented
@hauleth could you run `mix format` 🙏

2023-10-26 14:48 UTC, hauleth commented
Shure, in a moment.

2023-10-26 17:13 UTC, merged