perf: add back fullsweep_after to Task.Supervisor
Logflare/logflare pull request #2247
Opened 2024-11-04 15:55 UTC by Ziinc

Added back spawn_opt for Task.Supervisor, prevents garbage buildup.
Was removed in https://github.com/Logflare/logflare/commit/40db716e82cb3bc4041709f2aec8de6fe811cd53#diff-14a0c2e2cb2fe12cfea0794ab7c068ea2f25fa332f3fb7e0351e9d63b0266adfL81

2024-11-04 16:04 UTC, Ziinc commented
the spawn_opt gets forwarded to the underlying process
https://github.com/elixir-lang/elixir/blob/v1.17/lib/elixir/test/elixir/task/supervisor_test.exs#L31

2024-11-04 18:45 UTC, chasers requested changes
Removing this didn't change the memory usage profile at all.

And I think we need to do less GC'ing.

2024-11-05 16:15 UTC, Ziinc commented
As discussed, leaving this open for observation.

2024-11-07 13:57 UTC, chasers approved these changes

2024-12-04 14:55 UTC, Ziinc commented
Closing as memory isn't an issue now.

2024-12-04 14:55 UTC, closed without merging